#!/bin/bash

# if [ $EUID -ne 0 ]; then
#     exit 126
# fi
declare -A DIR_LIST
DIR_MOUNT=$HOME/.constellation/.mounts
DIR_MOUNT_Files=$DIR_MOUNT/Files
DIR_MOUNT_Books=$DIR_MOUNT/Books
DIR_MOUNT_NAS=$DIR_MOUNT/NAS

DIR_LIST[files]="${DIR_MOUNT_Files}"
DIR_LIST[books]="${DIR_MOUNT_Books}"
DIR_LIST[nas]="${DIR_MOUNT_NAS}"

function check_mount_dirs() {
    for dir in "${DIR_LIST[@]}"; do
        if [ ! -e "${dir}" ]; then
            echo "${dir} does not exist, creating..."
            mkdir -p "${dir}"
        fi
    done
}

case $1 in
    mount )
        check_mount_dirs
    ;;
esac